name: Build & Test Project
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:        
      - name: Install dependencies
        run: npm ci 
  job-3:
    runs-on: ubuntu-latest
    needs: [job-1, job-2]
    steps:
      - name: Run tests
        run: npm test
